swagger: '2.0'
info:
  description: This is restful service to manage users
  version: '1.0'
  title: Data - User Service
  termsOfService: 'http://springfox.io'
schemes:
  - http
host: 'localhost:9032'
basePath: /data/v1
tags:
  - name: User Service
    description: Data Service to allow user management
paths:
  /users:
    get:
      tags:
        - User Service
      summary: Get all the users
      operationId: gitUsers
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: meaningful_query_param
          in: query
          description: meaningful_query_param
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - User Service
      summary: Add a new user to the system
      operationId: addUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: payload
          description: payload
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  '/users/{id}':
    get:
      tags:
        - User Service
      summary: Get the user with the specified user id
      operationId: findUserWithID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: User id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/User'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  User:
    type: object
    allOf:
      - $ref: '#/definitions/NewUser'
      - required:
          - id
        properties:
          id:
            type: integer
            format: int64
  NewUser:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      ssn:
        type: string
